? "linkajme v6"

   Go_Fun()
   PQStatus()
   PQErrorMessage()
   PQSetErrorVerbosity()
   PQTransactionStatus()
   PQCmdTuples()
   PQMetaData()
   PQResultErrorMessage()
   PQSetDbLogin()
   PQResultStatus()
   PQconnectdb()
   PQtracecreate()
   PQtrace()
   PQPASS()
   PQHost()
   PQdb()
   PQexec()
   PQUser()   
   PQPort()
   PQTTY()
   PQOptions()
   PQIsNONBlocking()  
   PQSetNonBlocking()
   PQexecParams()
   PQfcount()
   PQProtocolVersion()
   PQlastrec()
   PQServerVersion()
   PQgetvalue()
   PQSetClientEncoding()
   PQClientEncoding()
   PQuntrace()
   PQOidValue()
   PQOidStatus()
   PQBinaryTuples()
   PQNTuples()
   PQNFields()
   PQFName()
   PQFTable()
   PQFType()
   PQFNumber()
   PQFMod()
   PQHOST()
   PQFSize()
   PQGetIsNull()
   Lo_Import()
   Lo_Export()
   Lo_Unlink()

   // hbct
   NumToken()
   Token()
   AtToken()
   DirName()
   FileSeek()
   FileDate()
   FileDelete()
   GetSecret()
   FileAttr()
   SetFAttr()
   StrFile()
   FileCopy()
   DirMake()

   // go.c 
   FileBase()
   FileExt()
   __RUN_SYSTEM()


   HB_SendMail()

   Hb_ZipOpen()
